import { type FormEvent, useState } from "react";
import type { StoredCase } from "../case-store.ts";

interface Props { onAnalyze: (source: string, title: string) => void; busy: boolean; error: string; history: StoredCase[]; onOpenCase: (item: StoredCase) => void; onClearHistory: () => void }

export function IntakeV04({ onAnalyze, busy, error, history, onOpenCase, onClearHistory }: Props) {
  const [source, setSource] = useState(""), [title, setTitle] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); onAnalyze(source, title); };
  return <><section className="intake"><div className="intake-copy"><div className="eyebrow">PostgreSQL plan triage · local only</div><h1>Evidence before advice.</h1><p>Paste a PostgreSQL execution plan. PGPlan Insight normalizes JSON or TEXT, identifies the strongest defensible signal, and defines what to test next.</p><div className="privacy"><span />Plans remain in local history until you manually clear them.</div></div><form className="plan-form" onSubmit={submit}><label htmlFor="case-title">Case title <span>optional</span></label><input id="case-title" maxLength={200} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Checkout query after index change" /><label htmlFor="plan-input">Plan evidence <span>JSON or TEXT</span></label><textarea id="plan-input" required spellCheck={false} value={source} onChange={(event) => setSource(event.target.value)} placeholder="Paste EXPLAIN ANALYZE in FORMAT JSON or TEXT" />{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><p>Large plans are analyzed off the UI thread.</p><button type="submit" disabled={busy}>{busy ? "Analyzing…" : <>Analyze and save <span>→</span></>}</button></div></form></section>{history.length > 0 && <section className="history-section"><div className="history-heading"><div><div className="section-kicker">Local case history</div><h2>Saved execution plans</h2><p>Stored only in this browser until manually cleared.</p></div><button className="danger-action" onClick={onClearHistory}>Clear all history</button></div><div className="history-list">{history.map((item) => <button key={item.id} onClick={() => onOpenCase(item)}><span><strong>{item.title}</strong><small>{new Date(item.createdAt).toLocaleString()} · {item.analysis.nodeCount} nodes · Evidence {item.analysis.score}/100</small></span><b>Open →</b></button>)}</div></section>}</>;
}
