import { useState } from "react";
import type { ReactNode } from "react";
import { analyzeOffThread } from "../analyze-client.ts";
import { buildComparisonReport, compareAnalyses, type ComparisonAttestation } from "../compare.ts";
import type { Analysis } from "../types.ts";
import { PlanMap } from "./PlanMap.tsx";
import { EnterprisePlanViewer } from "./EnterprisePlanViewer.tsx";
import { accessPathAssessment } from "../access-path-assessment.ts";
import { indexCandidate } from "../index-candidate.ts";
import type { DatabaseContext } from "../database-context.ts";
import { controlledExperiment } from "../controlled-experiment.ts";
import { CapturedEvidence } from "./EvidenceView.tsx";
import { evidenceClaims } from "../evidence-assessment.ts";
import type { StatisticsDiagnosis } from "../statistics-diagnosis.ts";

const ms = (value: number | null) => value == null ? "N/A" : `${value.toLocaleString(undefined, { maximumFractionDigits: 2 })} ms`;
const ratio = (value: number | null) => value == null ? "—" : `${value.toFixed(1)}×`;

function plannerChoiceContext(node: Analysis["planMap"][number]) {
  if (/Index Only Scan/i.test(node.nodeType)) return "The planner expected the index to supply the needed columns with limited heap access. Repeated loops, reads, or heap fetches can still make this path expensive.";
  if (/Bitmap/i.test(node.nodeType)) return "The planner expected several matching rows and chose to combine index matches before visiting heap pages.";
  if (/Index/i.test(node.nodeType)) return "The planner expected selective lookup or useful index ordering to cost less than reading the relation broadly.";
  if (/Seq Scan/i.test(node.nodeType)) return "The planner may have expected a broad result, a small relation, or random index access to cost more than a sequential read.";
  return "The captured plan identifies the access method, but catalog size, selectivity, visibility, and competing indexes are needed to explain the planner choice more precisely.";
}

function DataTable({ columns, rows }: { columns: string[]; rows: Array<Array<string | number>> }) {
  return <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>;
}

export function PlanViewer({ result }: { result: Analysis }) {
  return <EnterprisePlanViewer result={result} />;
}

export function TutorView({ result }: { result: Analysis }) {
  const lessons = result.planMap.slice(0, 8);
  return <section className="workspace-panel"><div className="section-kicker">Guided interpretation</div><h2>Plan Tutor</h2><p className="lede">Read this plan in execution order: validate the capture, inspect the dominant branch, then test the first evidence-backed change.</p><ol className="lesson-list"><li><strong>Check evidence quality</strong><p>This capture scores {result.score}/100 ({result.evidenceLevel}). Missing fields limit which conclusions are defensible.</p></li>{lessons.map((node) => <li key={node.path}><strong>{node.path} · {node.nodeType}</strong><p>{node.nodeType.includes("Scan") ? "This node retrieves rows. Compare returned rows, removed rows, and predicate indexability." : node.nodeType.includes("Join") ? "This node combines inputs. Repeated loops and estimate drift can amplify inner work." : "Compare inclusive time with approximate self time before treating this node as the cause."}</p><span>{ms(node.totalTime)} · {node.loops.toLocaleString()} loops · drift {ratio(node.estimateRatio)}</span></li>)}</ol></section>;
}

export function AccessPathsView({ result }: { result: Analysis }) {
  const rows = result.planMap.filter((node) => /scan/i.test(node.nodeType));
  return <section className="workspace-panel access-workbench"><div className="access-intro"><div><div className="section-kicker">Scans and predicates</div><h2>Access Paths</h2><p className="lede">How PostgreSQL located rows, what the captured evidence means, and what to validate before changing it.</p></div><div className="access-reading-guide" aria-label="How to read access paths"><div><strong>01 · Method</strong><span>Sequential, index, index-only, or bitmap access.</span></div><div><strong>02 · Evidence</strong><span>Rows, loops, reads, timing share, estimate drift, and predicate.</span></div><div><strong>03 · Decision</strong><span>Keep, review, or test—never assume an index is automatically better.</span></div></div></div>{rows.length ? <div className="access-list">{rows.map((node, index) => { const assessment = accessPathAssessment(node); const candidate = indexCandidate(node); return <article className="access-item" key={node.path}><div className="access-sequence">{String(index + 1).padStart(2, "0")}</div><div className="access-identity"><header><span className={`access-status ${assessment.level}`}>{assessment.label}</span><small>Operation #{node.rank}</small></header><h3>{node.nodeType}</h3><span>{node.relation === "—" ? "Relation not captured" : node.relation}</span><div className="access-metrics"><div><small>Actual rows</small><strong>{node.rows.toLocaleString()}</strong></div><div><small>Planned</small><strong>{node.plannedRows.toLocaleString()}</strong></div><div><small>Loops</small><strong>{node.loops.toLocaleString()}</strong></div><div><small>Reads</small><strong>{node.sharedReads.toLocaleString()}</strong></div></div></div><div className="access-explanation"><strong>{assessment.summary}</strong><p>{assessment.reason}</p><div className="access-evidence"><span>Predicate</span><code>{node.predicate || "Not captured"}</code></div><div className="access-evidence"><span>Validate next</span><p>{assessment.nextAction}</p></div>{candidate && <div className="access-candidate"><strong>Candidate to test—not a recommendation</strong><code>{candidate.sql}</code><small>{candidate.qualification}</small></div>}</div></article>; })}</div> : <Empty message="No scan nodes were detected. Access Paths is hidden from navigation when a plan has no scan operations." />}</section>;
}

export function WorkersView({ result }: { result: Analysis }) {
  const rows = result.planMap.filter((node) => /gather|parallel/i.test(node.nodeType) || node.workersPlanned > 0);
  return <section className="workspace-panel"><div className="section-kicker">Parallel execution</div><h2>Parallel Workers</h2><p className="lede">Planned-versus-launched workers reveal whether the expected parallel shape was available at runtime.</p>{rows.length ? <DataTable columns={["Path", "Node", "Workers planned", "Workers launched", "Rows", "Time"]} rows={rows.map((node) => [node.path, node.nodeType, node.workersPlanned, node.workersLaunched, node.rows.toLocaleString(), ms(node.totalTime)])} /> : <Empty message="No parallel worker evidence was captured." />}</section>;
}

export function EstimatesView({ result }: { result: Analysis }) {
  const rows = result.planMap.filter((node) => node.estimateRatio != null).sort((a, b) => (b.estimateRatio ?? 0) - (a.estimateRatio ?? 0));
  return <section className="workspace-panel"><div className="section-kicker">Planner accuracy</div><h2>Bad Estimates</h2><p className="lede">Large row-estimate drift can change join order, access paths, memory choices, and parallelism.</p>{rows.length ? <DataTable columns={["Path", "Node", "Relation", "Actual rows", "Estimate drift", "Loops", "Status"]} rows={rows.map((node) => [node.path, node.nodeType, node.relation, node.rows.toLocaleString(), ratio(node.estimateRatio), node.loops.toLocaleString(), (node.estimateRatio ?? 0) >= 10 ? "Review" : "Within range"])} /> : <Empty message="Actual and estimated row pairs were not available." />}</section>;
}

export function PlannerDiagnosticsView({ result, diagnosis }: { result: Analysis; diagnosis: StatisticsDiagnosis }) {
  const scans = result.planMap.filter((node) => /scan/i.test(node.nodeType)).map((node) => ({ node, assessment: accessPathAssessment(node) })).sort((a, b) => {
    const priority = (item: typeof a) => (item.assessment.level === "review" ? 1_000_000 : 0) + item.node.sharedReads * 100 + item.node.loops + item.node.timeShare * 1_000;
    return priority(b) - priority(a) || a.node.rank - b.node.rank;
  });
  const estimates = result.planMap.filter((node) => node.estimateRatio != null).sort((a, b) => (b.estimateRatio ?? 0) - (a.estimateRatio ?? 0));
  const materialEstimates = estimates.filter((node) => (node.estimateRatio ?? 0) >= 10);
  return <section className="workspace-panel planner-diagnostics">
    <div className="planner-heading"><div><div className="section-kicker">Planner decisions</div><h2>Planner diagnostics</h2><p className="lede">See which row-access choices performed material measured work and where row estimates first diverged. Planner cost explains a choice; actual time, reads, filtering, heap fetches, and loops show runtime work.</p></div><div className="planner-summary"><div><strong>{scans.filter(({ assessment }) => assessment.level === "review").length}</strong><span>access paths to review</span></div><div><strong>{materialEstimates.length}</strong><span>material estimate drifts</span></div></div></div>
    <section className="planner-reading-guide" aria-label="How to read Planner diagnostics"><div><span>01 · Measured work</span><strong>Start with time, reads, filtering, heap fetches, and repeated loops.</strong></div><div><span>02 · Planner choice</span><strong>An index is not automatically cheap; a sequential scan is not automatically wrong.</strong></div><div><span>03 · Estimate origin</span><strong>Investigate the deepest first row-estimate divergence before its parent symptoms.</strong></div></section>
    <section className="statistics-qualification planner-qualification" aria-label="Statistics qualification"><header><div><span>Estimate diagnosis</span><strong>{diagnosis.summary}</strong></div><b className={`statistics-classification ${diagnosis.classification}`}>{diagnosis.classification}</b></header><div className="statistics-qualification-grid"><div><small>First relevant divergence</small><p>{diagnosis.node ? `Operation ${diagnosis.node.rank} · ${diagnosis.node.nodeType} · ${diagnosis.node.relation}` : "None above 10×"}</p></div><div><small>Captured evidence</small><p>{diagnosis.evidence}</p></div><div><small>Not established</small><p>{diagnosis.unknown}</p></div><div><small>Controlled next step</small><p>{diagnosis.nextAction}</p></div></div></section>
    <section className="planner-section"><header><div><span>01</span><strong>Access-path review</strong></div><small>Ranked by measured contribution · {scans.length} scan{scans.length === 1 ? "" : "s"}</small></header>{scans.length ? <div className="planner-access-list">{scans.map(({ node, assessment }, index) => <details className={`planner-access-item ${assessment.level}`} key={node.path} open={index === 0 && assessment.level === "review"}><summary><span className={`access-status ${assessment.level}`}>{assessment.label}</span><span className="planner-operation"><strong>Operation {node.rank} · {node.nodeType}</strong><small>{node.relation === "—" ? "Relation not captured" : node.relation}</small></span><span><small>Time share</small><strong>{node.timeShare.toFixed(1)}%</strong></span><span><small>Reads</small><strong>{node.sharedReads.toLocaleString()}</strong></span><span><small>Loops</small><strong>{node.loops.toLocaleString()}</strong></span><b>Explain</b></summary><div className="planner-access-body"><div><span className="planner-body-label">Measured interpretation</span><strong>{assessment.summary}</strong><p>{assessment.reason}</p></div><div className="planner-choice"><span className="planner-body-label">Why PostgreSQL may have chosen it</span><p>{plannerChoiceContext(node)}</p><small>Bounded hypothesis: confirm relation size, selectivity, statistics, visibility map, and competing indexes with Database Context.</small></div><dl><div><dt>Actual / planned rows</dt><dd>{node.rows.toLocaleString()} / {node.plannedRows.toLocaleString()}</dd></div><div><dt>Estimate drift</dt><dd>{ratio(node.estimateRatio)}</dd></div><div><dt>Predicate</dt><dd><code>{node.predicate || "Not captured"}</code></dd></div><div><dt>Validate next</dt><dd>{assessment.nextAction}</dd></div></dl></div></details>)}</div> : <Empty message="No scan operation was captured, so no access-path claim can be made from this plan." />}</section>
    <section className="planner-section estimate-section"><header><div><span>02</span><strong>Row-estimate evidence</strong></div><small>Material drift first · parent symptoms retained</small></header>{estimates.length ? <div className="estimate-list"><div className="estimate-head"><span>Operation</span><span>Relation</span><span>Planned</span><span>Actual</span><span>Drift</span><span>Interpretation</span></div>{estimates.map((node) => { const isOrigin = diagnosis.node?.path === node.path; const material = (node.estimateRatio ?? 0) >= 10; return <div className={`estimate-row ${material ? "review" : ""} ${isOrigin ? "origin" : ""}`} key={node.path}><span><strong>Operation {node.rank} · {node.nodeType}</strong></span><span>{node.relation}</span><span>{node.plannedRows.toLocaleString()}</span><span>{node.rows.toLocaleString()}</span><span>{ratio(node.estimateRatio)}</span><span>{isOrigin ? "Investigate first: deepest material divergence" : material ? "May inherit or amplify earlier drift" : "Within the current 10× threshold"}</span></div>; })}</div> : <Empty message="Actual-versus-planned row pairs were not captured." />}</section>
  </section>;
}

export function RecommendationsView({ result, context, qualification, candidateExperiments }: { result: Analysis; context: DatabaseContext | null; qualification?: ReactNode; candidateExperiments?: ReactNode }) {
  return <section className="workspace-panel recommendations-workbench"><div className="recommendations-heading"><div><div className="section-kicker">Evidence-led tuning</div><h2>Findings</h2><p className="lede">Start with the strongest captured signal and test one bounded change. Estimated cost is context—not runtime proof.</p></div><aside><strong>{context ? "Database context applied" : "Plan-only boundary"}</strong><span>{context ? `${context.relations.length} sanitized relation(s) qualify catalog assumptions. Runtime evidence still comes from this plan.` : "Indexes, types, table size, statistics freshness, and workload recurrence remain unknown until context is imported."}</span></aside></div>{qualification}<section className="recommendation-section"><header><div><span>01</span><strong>Prioritized investigations</strong></div><small>{result.findings.length} check{result.findings.length === 1 ? "" : "s"} · measured evidence first</small></header><div className="recommendation-list">{result.findings.map((finding, index) => { const experiment = controlledExperiment(finding); const claims = evidenceClaims(result, finding); return <details className="finding-investigation" key={finding.id} open={index === 0}><summary><span className="recommendation-rank">{String(index + 1).padStart(2, "0")}</span><span className={`severity ${finding.severity}`}>{finding.severity}</span><span className="finding-title"><strong>{finding.title}</strong><small>{finding.evidence}</small></span><span className="finding-disclosure">Review</span></summary><div className="finding-investigation-body"><section className="finding-action" aria-label={`Controlled action for ${finding.title}`}><span>Test next</span><strong>{experiment.action}</strong><small>One change only; compare a representative after plan before accepting it.</small></section><div className="evidence-classifications" aria-label={`Evidence classification for ${finding.title}`}>{claims.map((claim) => <div className={`${claim.classification} ${claim.status}`} key={claim.classification}><span>{claim.classification}</span><strong>{claim.label}</strong><p>{claim.detail}</p></div>)}</div><details className="finding-guardrails"><summary>Validation guardrails</summary><dl><div><dt>Prerequisites</dt><dd>{experiment.prerequisites.join(" ")}</dd></div><div><dt>Success gate</dt><dd>{experiment.successCriteria.join(" ")}</dd></div><div><dt>Rollback boundary</dt><dd>{experiment.rollback}</dd></div></dl></details></div></details>; })}</div></section>{candidateExperiments}<CapturedEvidence result={result} /></section>;
}

export function FixValidationView({ current }: { current: Analysis }) {
  const [source, setSource] = useState("");
  const [after, setAfter] = useState<Analysis | null>(null);
  const [error, setError] = useState("");
  const [attestation, setAttestation] = useState<ComparisonAttestation>({ sameStatement: false, sameParameters: false, comparableEnvironment: false, repeatedCapture: false });
  const compare = async () => { try { setAfter(await analyzeOffThread(source)); setError(""); } catch (caught) { setAfter(null); setError(caught instanceof Error ? caught.message : "Comparison failed."); } };
  const result = after ? compareAnalyses(current, after, attestation) : null;
  const setCheck = (name: keyof ComparisonAttestation) => setAttestation((value) => ({ ...value, [name]: !value[name] }));
  const download = () => { if (!after || !result) return; const url = URL.createObjectURL(new Blob([buildComparisonReport(current, after, result)], { type: "text/markdown" })); const link = document.createElement("a"); link.href = url; link.download = "pgplan-fix-validation.md"; link.click(); URL.revokeObjectURL(url); };
  const declarations = [
    ["sameStatement", "Same SQL shape", "The tested change did not alter the business question."],
    ["sameParameters", "Equivalent representative parameters", "Before and after use equivalent, representative values."],
    ["comparableEnvironment", "Comparable settings, cache state and concurrency", "The execution environment is comparable."],
    ["repeatedCapture", "Result repeated", "The result occurred more than once under representative conditions."],
  ] as const;
  const blockers = result?.comparability.filter((check) => check.status === "blocker").length ?? 0;
  const warnings = result?.comparability.filter((check) => check.status === "warning").length ?? 0;
  return <section className="workspace-panel validation-workbench">
    <div className="validation-heading"><div><div className="section-kicker">Before / after proof</div><h2>Validate fix</h2><p className="lede">Determine whether one controlled change produced a comparable, repeatable improvement. A single faster execution remains inconclusive.</p></div><aside><strong>Approval boundary</strong><span>This compares captured plans. It does not approve a production change or prove workload-wide benefit.</span></aside></div>
    <dl className="validation-baseline" role="group" aria-label="Captured before-plan baseline"><div><dt>Before runtime</dt><dd>{current.executionTime == null ? "Not captured" : `${current.executionTime.toLocaleString()} ms`}</dd></div><div><dt>Shared reads</dt><dd>{current.metrics.rootSharedReads.toLocaleString()}</dd></div><div><dt>Temporary blocks</dt><dd>{current.metrics.rootTempBlocks.toLocaleString()}</dd></div><div><dt>Operations</dt><dd>{current.nodeCount.toLocaleString()}</dd></div></dl>
    <section className="validation-stage"><header><div><span>01</span><h3>Establish comparability</h3></div><small>All four declarations are required for an improvement verdict</small></header><p className="validation-attestation-note"><strong>Operator declarations—not verified from the plan:</strong> confirm these conditions from the capture process before relying on the result.</p><fieldset className="comparison-attestations"><legend>Capture declarations</legend>{declarations.map(([name, label, help]) => <label key={name}><input type="checkbox" checked={attestation[name]} onChange={() => setCheck(name)} /><span><strong>{label}</strong><small>{help}</small></span></label>)}</fieldset><label className="after-plan-input"><span><strong>After plan</strong><small>TEXT or FORMAT JSON · include EXPLAIN ANALYZE for measured comparison</small></span><textarea aria-label="After plan evidence" value={source} onChange={(event) => setSource(event.target.value)} placeholder="Paste the after/fixed execution plan" /></label><div className="validation-actions"><button onClick={compare} disabled={!source.trim()}>Run comparison gate</button><small>No SQL is executed and nothing is transmitted.</small></div>{error && <p className="form-error" role="alert">{error}</p>}</section>
    {after && result && <><section className={`validation-verdict ${result.verdict === "Improved" ? "improved" : result.verdict === "Regressed" ? "regressed" : "neutral"}`} aria-label="Validation verdict"><div><span>DBA verdict</span><strong>{result.verdict}</strong><small>{result.comparable ? `${Math.abs(result.runtimeDeltaPercent ?? 0).toFixed(1)}% ${Number(result.runtimeDeltaPercent) < 0 ? "faster" : "slower"}` : "Resolve every blocker before making a performance claim."}</small></div><dl><div><dt>Blockers</dt><dd>{blockers}</dd></div><div><dt>Warnings</dt><dd>{warnings}</dd></div><div><dt>Runtime delta</dt><dd>{result.runtimeDeltaPercent == null ? "N/A" : `${result.runtimeDeltaPercent >= 0 ? "+" : ""}${result.runtimeDeltaPercent.toFixed(1)}%`}</dd></div><div><dt>Evidence quality</dt><dd>{current.score} → {after.score}</dd></div></dl></section>
      <section className="validation-stage"><header><div><span>02</span><h3>Comparability gate</h3></div><small>Blocker, warning, and pass are shown independently</small></header><div className="comparability-gate">{result.comparability.map((check) => <div className={check.status} key={check.id}><strong>{check.status} · {check.label}</strong><span>{check.detail}</span></div>)}</div></section>
      <section className="validation-stage"><header><div><span>03</span><h3>Measured changes</h3></div><small>Negative delta means less measured work</small></header><DataTable columns={["Metric", "Before", "After", "Difference"]} rows={result.metrics.map((row) => [row.label, row.before ?? "N/A", row.after ?? "N/A", row.delta == null ? "N/A" : `${row.delta >= 0 ? "+" : ""}${row.delta.toFixed(1)}%`])} /></section>
      <section className="validation-stage"><header><div><span>04</span><h3>Structural plan changes</h3></div><small>Matched by node type, relation, predicate, and depth—not ordinal alone</small></header>{result.accessPathChanges.length ? <details className="structural-changes"><summary>{result.accessPathChanges.length} changed, added, or removed operations <b>Review matches</b></summary><DataTable columns={["Plan position", "Before operation", "After operation", "Match confidence"]} rows={result.accessPathChanges.map((row) => [row.path, row.before, row.after, row.confidence])} /></details> : <p className="validation-empty">No structural node-type change was found after identity matching.</p>}</section>
      <section className="validation-decision"><div><strong>Success gate</strong><p>Accept only when representative repeated runtime improves materially and reads, temporary I/O, WAL, row accuracy, or access paths do not introduce an unacceptable regression.</p></div><div><strong>Rollback boundary</strong><p>Revert only the tested change when the gate fails, plan stability worsens, or representative workload risk increases.</p></div><button className="secondary-action" onClick={download}>Export validation report</button></section></>}
  </section>;
}

export function NativePlanMap({ result }: { result: Analysis }) { return <PlanMap result={result} />; }
function Empty({ message }: { message: string }) { return <div className="empty-message">{message}</div>; }
