import { useMemo, useRef, useState } from "react";
import { formatBytes, formatDuration, parseWorkloadSnapshot, rankWorkload, type WorkloadSnapshot } from "../workload-triage.ts";

interface Props { onBack: () => void; onInvestigate: (fingerprint: string) => void }

const example: WorkloadSnapshot = { version: 1, provenance: { collectedAt: "2026-09-12T14:00:00Z", postgresVersion: "16.4", statsResetAt: "2026-09-12T13:00:00Z", collector: "pgplan-workload-sql", redacted: true }, statements: [
  { fingerprint: "statement-938471", calls: 84, totalExecTimeMs: 486_200, meanExecTimeMs: 5_788.1, rows: 84, sharedHitBlocks: 218_430, sharedReadBlocks: 31_240, tempReadBlocks: 18_400, tempWrittenBlocks: 18_910, walBytes: 0 },
  { fingerprint: "statement-204118", calls: 148_302, totalExecTimeMs: 322_500, meanExecTimeMs: 2.17, rows: 148_302, sharedHitBlocks: 904_000, sharedReadBlocks: 210, tempReadBlocks: 0, tempWrittenBlocks: 0, walBytes: 0 },
  { fingerprint: "statement-771205", calls: 420, totalExecTimeMs: 184_000, meanExecTimeMs: 438.1, rows: 8_920, sharedHitBlocks: 42_000, sharedReadBlocks: 58_400, tempReadBlocks: 0, tempWrittenBlocks: 0, walBytes: 0 },
] };

export function WorkloadTriageView({ onBack, onInvestigate }: Props) {
  const [source, setSource] = useState(""), [snapshot, setSnapshot] = useState<WorkloadSnapshot | null>(null), [error, setError] = useState("");
  const file = useRef<HTMLInputElement>(null);
  const ranked = useMemo(() => snapshot ? rankWorkload(snapshot) : [], [snapshot]);
  const analyze = () => { try { setSnapshot(parseWorkloadSnapshot(source)); setError(""); requestAnimationFrame(() => window.scrollTo({ top: 0 })); } catch (caught) { setSnapshot(null); setError(caught instanceof Error ? caught.message : "Workload snapshot could not be analyzed."); } };
  const read = async (selected?: File) => { if (!selected) return; if (selected.size > 2_000_000) { setError("Workload snapshot exceeds the 2 MB limit."); return; } try { setSource(await selected.text()); setError(""); } catch { setError("Workload snapshot could not be read."); } };
  return <section className="workload-triage">
    <header className="triage-heading"><div><div className="section-kicker">Workload triage</div><h1>Find the statement consuming database time.</h1><p>Rank a sanitized <code>pg_stat_statements</code> snapshot before opening an individual execution plan.</p></div><button onClick={onBack}>Back to plan analysis</button></header>
    {!snapshot ? <div className="triage-intake">
      <section><h2>Import a sanitized snapshot</h2><p>The collector excludes SQL text, users, database names, hosts, parameters and credentials. Processing remains in this browser.</p><label htmlFor="workload-source">Workload evidence <span>JSON · 2 MB maximum · 5,000 statements</span></label><textarea id="workload-source" value={source} onChange={(event) => setSource(event.target.value)} spellCheck={false} placeholder="Paste the output from pgplan-workload-snapshot.sql" />{error && <p className="triage-error" role="alert">{error}</p>}<div className="triage-actions"><button onClick={() => { setSource(JSON.stringify(example, null, 2)); setError(""); }}>Load safe example</button><button onClick={() => file.current?.click()}>Choose JSON file</button><input ref={file} className="file-input" type="file" accept=".json,application/json" onChange={(event) => void read(event.target.files?.[0])} /><button className="primary" disabled={!source.trim()} onClick={analyze}>Prioritize workload</button></div></section>
      <aside><h2>What this establishes</h2><dl><div><dt>Observed</dt><dd>Calls, cumulative execution time, rows, blocks, temporary I/O and WAL attributed by PostgreSQL.</dd></div><div><dt>Derived</dt><dd>Database-time share and deterministic priority within this snapshot.</dd></div><div><dt>Unknown</dt><dd>Root cause, p95 latency, concurrency, lock waits, cache state and whether a proposed change will help.</dd></div></dl><a href="/pgplan-workload-snapshot.sql" download>Download read-only collector SQL</a></aside>
    </div> : <>
      <section className="triage-boundary"><strong>Priority is measured, cause is not yet established.</strong><span>{snapshot.statements.length.toLocaleString()} statements · PostgreSQL {snapshot.provenance.postgresVersion} · collected {new Date(snapshot.provenance.collectedAt).toLocaleString()}</span><button onClick={() => setSnapshot(null)}>Import another snapshot</button></section>
      <div className="triage-table-wrap"><table className="triage-table"><thead><tr><th>Priority</th><th>Fingerprint</th><th>Database time</th><th>Mean / calls</th><th>Read evidence</th><th>Primary review</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{ranked.map((row) => <tr key={row.fingerprint}><td><strong>{row.rank}</strong></td><td><strong>{row.fingerprint}</strong><span>{row.databaseTimeShare.toFixed(1)}% of captured time</span></td><td><strong>{formatDuration(row.totalExecTimeMs)}</strong><span>Cumulative</span></td><td><strong>{formatDuration(row.meanExecTimeMs)}</strong><span>{row.calls.toLocaleString()} calls</span></td><td><strong>{row.sharedReadBlocks.toLocaleString()} blocks</strong><span>{row.tempReadBlocks + row.tempWrittenBlocks ? `${(row.tempReadBlocks + row.tempWrittenBlocks).toLocaleString()} temp` : `${row.sharedHitBlocks.toLocaleString()} hits`}</span></td><td><strong>{row.focus}</strong><span>{row.focusEvidence}{row.walBytes ? ` WAL ${formatBytes(row.walBytes)}.` : ""}</span></td><td><button onClick={() => onInvestigate(row.fingerprint)}>Start investigation <span>›</span></button></td></tr>)}</tbody></table></div>
      <section className="triage-next"><div><strong>Controlled next step</strong><p>Capture a representative <code>EXPLAIN (ANALYZE, BUFFERS, SETTINGS, WAL, FORMAT JSON)</code> for the selected fingerprint in a safe environment. Workload counters prioritize the investigation; the plan supplies node-level evidence.</p></div><div><strong>Snapshot boundary</strong><p>Counters are cumulative since the statistics reset and may combine different parameter values. Compare equal collection windows before claiming workload improvement.</p></div></section>
    </>}
  </section>;
}
